import LocalizedStrings from 'react-localization';

var strings = new LocalizedStrings({
	en:{
		dashboard: "Dashboard",
		myDashboard: "My Dashboard",
		myTeam: "My Team",
		myCompany: "My Company",
		trainingStatus: "Training Status",
		pastDue: "Past Due",
		signaturesNeeded: "Signatures needed",
		itemsPastDue: "Items past due",
		trainingPastDue: "Training Past Due",
		trainingComplete: "Training Complete",
		trainingCommingDue: "Training Comming Due",
		newComments: "New comments",
		newActivity: "New Activity",
		newAssignments: "New assignments",
		savedReports: "Saved reports",
		newActivities: "New Activities",
		itemName: "Item name",
		workflow: "Workflow",
		delegate: "Delegate",
		sign: "Sign",
		reject: "Reject",
		type: "Type",
		dueDate: "Due Date",
		author: "Author",
		reviewDate: "Review Date",
		status: "Status",
		training: "Training",
		myTraining: "My Training",
		myDirectReports: "My Direct Reports",
		myCompany: "My Company",
		trainingPipeline: "Training pipeline",
		trainingItemsCommingDue: "training items coming due",
		trainingStatus: "Training Status",
		trainingItems: "training items",
		documentName: "Document Name",
		train: "Train",
		due: "Due",
		date: "Date",
		userName: "User Name",
		documents: "Documents",
		myDocuments: "My Documents",
		stateOfDocuments: "State of Documents",
		documentsCommingUpForReview: "Documents comming up for review",
		newDocumentsAssigments: "new Documents Assignments",
		documentsWithNewComments: "documents with new comments",
		category: "Category",
		commentAuthor: "Comment Author",
		dateOfComment: "Date of Comment",
		audits: "Audits",
		stateOfAudits: "State of audits",
		auditSchedule: "Audits Schedule",
		auditsWithRecentActivity: "audits with recent activity",
		auditsWithNewComments: "audits with new comments",
		targeted: "Targeted",
		scheduled: "Scheduled",
		execution: "Execution",
		pubFinalReport: "Pub Final Report",
		sendToAuditee: "Send to Auditee",
		activeWorkflows: "Active Workflows",
		jan: "Jan",
		feb: "Feb",
		mar: "Mar",
		apr: "Apr",
		may: "May",
		jun: "Jun",
		jul: "Jul",
		ago: "Ago",
		sep: "Sep",
		oct: "Oct",
		nov: "Nov",
		dic: "Dic",
		auditId: "Audit ID",
		siteName: "Site Name",
		state: "State",
		leadAuthor: "Lead Author",
		observations: "Observations",
		critical: "Critical",
		major: "Major",
		minor: "Minor",
		comment: "Comment",
		stateOfObservation: "State of observations",
		unresolvedObservation: "Unresolved observations",
		observationsWithRecentActivity: "observations with recent activity",
		observationsWithNewComments: "observations with new comments",
		observationId: "Observation ID",
		severity: "Severity",
		actionDue: "Action Due",
		auditorAssignee: "Auditor Assignee",
		auditeeAssignee: "Auditee Assignee",
		issues: "Issues",
		draft: "Draft",
		awaitingApproval: "Awaiting Approval",
		implementation: "Implementation",
		finalReview: "Final Review",
		closed: "Closed",
		awaitingEC: "Awaiting E.C.",
		effective: "Effective",
		failed: "Failed",
		stateOfIssues: "State of Issues",
		unresolvedIssues: "Unresolved Issues",
		issuesWithRecentActivity: "issues with recent activity",
		issuesWithNewComments: "issues with new comments",
		issueId: "Issue ID",
		leadInvestigator: "Lead Investigator",
		capas: "capas",
		complete: "Complete",
		draft: "Draft",
		implementation: "Implementation",
		stateOfCapas: "State of CAPAs",
		unresolvedCapas: "Unresolved CAPAs",
		myCapas: "My CAPAs",
		myIssues: "My Issues",
		myObservations: "My Observations",
		myAdutis: "My Audits",
		capasWithRecentActivity: "CAPAs with recent activity",
		capasWithNewComments: "CAPAs with new comments",
		capaId: "Capa ID",
		headline: "Headline",
		state: "State",
		impDate: "Imp. Date"
	},
	es:{
		dashboard: "Tablero",
		myDashboard: "Mi Tablero",
		myTeam: "Mi Equipo",
		myCompany: "My Empresa",
		trainingStatus: "Estado de Entrenamiento",
		pastDue: "Vencido",
		signaturesNeeded: "Firmas necesarias",
		itemsPastDue: "Artculos vencidos",
		trainingPastDue: "Entrenamiento vencido",
		trainingComplete: "Entrenamiento Completo",
		trainingCommingDue: "Entrenamiento por vencerse",
		newComments: "Nuevos Comentarios",
		newActivity: "Nueva Actividad",
		newAssignments: "Nueva Asignación",
		savedReports: "Informes Guardados",
		newActivities: "Nuevas Actividades",
		itemName: "Nombre del Articulo",
		workflow: "Flujo de Trabajo",
		delegate: "Delegar",
		sign: "Firmar",
        reject: "Rechazar",
		type: "Tipo",
        dueDate: "Vencimiento",
		author: "Autor",
		reviewDate: "Fecha de revisión",
		status: "Estado",
		training: "Entrenamiento",
		myTraining: "Mi entrenamiento",
		myDirectReports: "Mis Informes Directos",
		myCompany: "Mi Empresa",
		trainingPipeline: "canal de entrenamiento",
		trainingItemsCommingDue: "articulos de entrenamiento que vencen",
		trainingStatus: "Estado del Entrenamiento",
		trainingItems: "Articulos de Entrenamientos",
		documentName: "Nombre del Documento",
		train: "Entrenar",
		due: "Debido",
		date: "Fecha",
		userName: "Usuario",
		documents: "Documentos",
		myDocuments: "Mis Documentos",
		stateOfDocuments: "Esto de Documentos",
		documentsCommingUpForReview: "Documentos con fecha de entrega pronto",
		newDocumentsAssigments: "Nuevos documentos de asignados",
		documentsWithNewComments: "Documentos con nuevos comentarios",
		category: "Categoría",
		commentAuthor: "Autor",
		dateOfComment: "Fecha de comentario",
		audits: "Auditorías",
		stateOfAudits: "Estado de las auditorías",
		auditSchedule: "Horario de auditorías",
		auditsWithRecentActivity: "auditorías con actividad reciente",
		auditsWithNewComments: "auditorías con nuevos comentarios",
		targeted: "Apuntado",
		scheduled: "Agendado",
		execution: "Ejecución",
		pubFinalReport: "Informe Final",
		sendToAuditee: "Enviar a auditado",
		activeWorkflows: "Los flujos de trabajo",
		jan: "Ene",
		feb: "Feb",
		mar: "Mar",
		apr: "Abr",
		may: "May",
		jun: "Jun",
		jul: "Jul",
		ago: "Ago",
		sep: "Sep",
		oct: "Oct",
		nov: "Nov",
		dic: "Dic",
		auditId: "Auditoría ID",
		siteName: "Nombre del sitio",
		state: "Estado",
		leadAuthor: "Autor principal",
		observations: "Observaciones",
		critical: "Crítico",
		major: "Mayor",
		minor: "Menor",
		comment: "Comentario",
		stateOfObservation: "Estado de observaciones",
		unresolvedObservation: "observaciones no resueltas",
		observationsWithRecentActivity: "observaciones con actividad reciente",
		observationsWithNewComments: "observaciones con nuevos comentarios",
		observationId: "Observación ID",
		severity: "Gravedad",
		actionDue: "acción debida",
		auditorAssignee: "Auditor Asignado",
		auditeeAssignee: "Auditado Asignado",
		issues: "Problemas",
		draft: "Borrador",
		awaitingApproval: "Esperando Aprobacion",
		implementation: "Implementación",
		finalReview: "Revisión Final",
		closed: "Cerrado",
		awaitingEC: "Esperando E.C.",
		effective: "Effectivo",
		failed: "Fallado",
		stateOfIssues: "Estado de Problemas",
		unresolvedIssues: "problemas no resueltas",
		issuesWithRecentActivity: "problemas con actividad reciente",
		issuesWithNewComments: "problemas con nuevos comentarios",
		issueId: "Problema ID",
		leadInvestigator: "Investigador Principal",
		capas: "capas",
		complete: "Completo",
		implementation: "Implementación",
		stateOfCapas: "Estado de CAPAs",
		unresolvedCapas: "CAPAs no Resuelto",
		myCapas: "Mis CAPAs",
		myIssues: "Mis Problemas",
		myObservations: "Mis Observaciones",
		myAdutis: "My Auditorias",
		capasWithRecentActivity: "CAPAs con actividad reciente",
		capasWithNewComments: "CAPAs con nuevos comentarios",
		capaId: "CAPA ID",
		headline: "Titular",
		state: "Estado",
		impDate: "Imp. Fecha"
	}
});

var lang = localStorage.getItem("lang");

strings.setLanguage(lang ? lang : 'en');
export default strings;
